apiVersion: v1
kind: Deployment
metadata:
  name: esphome
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        diun.enable: "true"
    spec:
	  containers:
        - image: esphome/esphome
          name: esphome
          resources: {}
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /etc/localtime
              name: esphome-claim1
              readOnly: true
      restartPolicy: Always
      volumes:
      - name: config
        nfs: 
          server: nas.local
          path: /k3s-volumes/esphome/
