apiVersion: v1
kind: Pod
metadata:
  name: esphome
spec:
  hostNetwork: true
  volumes:
  - name: config
    nfs:
      server: nas.local
      path: /data/k3s-volumes/esphome/
  - name: cache
    emptyDir: {}
  containers:
  - name: esphome
    image: esphome/esphome
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /cache
      name: cache
    - mountPath: /config
      name: config
