apiVersion: v1
kind: Pod
metadata:
  name: esphome
spec:
  volumes:
    - name: config
      nfs:
        server: nas.local
        path: /data/k3s-volumes/esphome/
  containers:
    - name: esphome
      image: esphome/esphome
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /config
          name: config
